import 'package:flutter/material.dart';

class AppI18n {
  static Locale _locale = const Locale('ar');
  static Locale get locale => _locale;
  static bool get isArabic => _locale.languageCode == 'ar';

  static void setLocale(Locale locale) {
    _locale = locale.languageCode == 'en' ? const Locale('en') : const Locale('ar');
  }

  static String roleLabel(String role) {
    switch (role) {
      case 'gm':
        return isArabic ? 'المدير العام' : 'General Manager';
      case 'manager':
        return isArabic ? 'مدير' : 'Manager';
      default:
        return isArabic ? 'موظف' : 'Employee';
    }
  }

  static const Map<String, String> _ar = {
    'Hama Work': 'Hama Work',
    'Internal Work & Communication': 'إدارة العمل والتواصل الداخلي',
    'Sign in': 'تسجيل الدخول',
    'Signing in...': 'جارٍ تسجيل الدخول...',
    'Username': 'اسم المستخدم',
    'Password': 'كلمة المرور',
    'Dashboard': 'الرئيسية',
    'My Tasks': 'مهامي',
    'Team Tasks': 'مهام الفريق',
    'Tasks': 'المهام',
    'Messages': 'الرسائل',
    'Notifications': 'التنبيهات',
    'Settings': 'الإعدادات',
    'Language': 'اللغة',
    'Arabic': 'العربية',
    'English': 'الإنجليزية',
    'Choose language': 'اختر اللغة',
    'Send': 'إرسال',
    'New Task': 'مهمة جديدة',
    'New Message': 'رسالة جديدة',
    'Title': 'العنوان',
    'Title *': 'العنوان *',
    'Description': 'الوصف',
    'Description *': 'الوصف *',
    'Responsible': 'المسؤول',
    'Follower': 'المتابع',
    'Deadline': 'الموعد النهائي',
    'Priority': 'الأولوية',
    'Normal': 'عادية',
    'Urgent': 'عاجلة',
    'Status': 'الحالة',
    'Not Started': 'لم تبدأ',
    'In Progress': 'قيد التنفيذ',
    'Ready for Completion': 'جاهزة للإنجاز',
    'Completed': 'مكتملة',
    'Overdue': 'متأخرة',
    'Cancelled': 'ملغاة',
    'Save': 'حفظ',
    'Cancel': 'إلغاء',
    'Create': 'إنشاء',
    'Close': 'إغلاق',
    'Reopen': 'إعادة فتح',
    'Confirm': 'تأكيد',
    'Evaluate': 'تقييم',
    'Task Chat': 'محادثة المهمة',
    'Reply': 'رد',
    'Write a comment...': 'اكتب تعليقًا...',
    'Information': 'معلومة',
    'Action Required': 'إجراء مطلوب',
    'Task': 'مهمة',
    'Progress': 'التقدم',
    'Stages': 'أجزاء المهمة',
    'Chat': 'المحادثات',
    'Task Actions': 'إجراءات المهمة',
    'How progress works': 'طريقة متابعة التقدم',
    'Everyone': 'الجميع',
    'Selected users': 'مستخدمون محددون',
    'Recipients': 'المستلمون',
    'Seen': 'شوهدت',
    'Unread': 'غير مقروء',
    'No tasks': 'لا توجد مهام',
    'No messages': 'لا توجد رسائل',
    'No notifications': 'لا توجد تنبيهات',
    'Could not load recipients': 'تعذر تحميل المستلمين',
    'No recipients': 'لا يوجد مستلمون',
    'Select at least one recipient': 'اختر مستلمًا واحدًا على الأقل',
    'Mark all read': 'تحديد الكل كمقروء',
    'Mark read': 'تحديد كمقروء',
    'Logout': 'تسجيل الخروج',
    'Language saved': 'تم حفظ اللغة',
    'Today': 'اليوم',
    'All': 'الكل',
    'All statuses': 'كل الحالات',
    'Needs Your Attention': 'يحتاج إلى انتباهك',
    'Overdue Tasks': 'المهام المتأخرة',
    'Ready Tasks': 'المهام الجاهزة للإنجاز',
    'Unread Messages': 'الرسائل غير المقروءة',
    'Unread Notifications': 'التنبيهات غير المقروءة',
    'Only the General Manager can create tasks': 'المدير العام فقط يمكنه إنشاء المهام',
    'Task created successfully': 'تم إنشاء المهمة بنجاح',
    'Message sent successfully': 'تم إرسال الرسالة بنجاح',
    'Task updated successfully': 'تم تحديث المهمة بنجاح',
    'Could not sign in': 'تعذر تسجيل الدخول',
    'Error': 'خطأ',
    'Select a user': 'اختر مستخدمًا',
    'No follower': 'بدون متابع',
    'Evidence required': 'إثبات الإنجاز مطلوب',
    'Manager confirmation before completion': 'تأكيد المدير قبل الإكمال',
    'Score 1-10': 'التقييم من 1 إلى 10',
    'Evaluation comment': 'تعليق التقييم',
    'Confirm completion': 'تأكيد الإكمال',
    'Request completion': 'طلب الإكمال',
    'General Manager': 'المدير العام',
    'Start': 'بدء',
    'Yes': 'نعم',
    'No': 'لا',
    'Task Status Updated': 'تم تحديث حالة المهمة',
    'Task Deadline Approaching': 'الموعد النهائي للمهمة يقترب',
    'Task Overdue': 'المهمة متأخرة',
    'Task Ready for Completion': 'المهمة جاهزة للإنجاز',
    'Task Completed': 'اكتملت المهمة',
    'Task Cancelled': 'تم إلغاء المهمة',
    'Welcome': 'مرحبًا',
    'Good Morning': 'صباح الخير',
    'Good Afternoon': 'مساء الخير',
    'Good Evening': 'مساء الخير',
    'Keep work moving forward': 'خلّي الشغل دايمًا متحرك للأمام',
    'Manager': 'مدير',
    'Employee': 'موظف',
    'Total quantity': 'إجمالي الكمية',
    'Unit': 'الوحدة',
    'Progress & Daily Achievement': 'التقدم والإنجاز اليومي',
    'Add daily achievement': 'إضافة إنجاز يومي',
    'No total quantity was defined for this task.': 'لم يتم تحديد إجمالي كمية لهذه المهمة.',
    'No daily achievement recorded yet.': 'لم يتم تسجيل إنجاز يومي بعد.',
    'Task Stages': 'أجزاء المهمة',
    'Add stage': 'إضافة جزء',
    'No stages defined.': 'لم يتم تقسيم المهمة إلى أجزاء بعد.',
    'Stage name': 'اسم الجزء',
    'Stage quantity': 'كمية الجزء',
    'Daily Work Log': 'سجل العمل اليومي',
    'No daily work recorded yet.': 'لا يوجد إنجاز يومي مسجل بعد.',
    'updates': 'تحديثات',
    'Daily achievement': 'الإنجاز اليومي',
  'Notification': 'تنبيه',
  'Task Update': 'تحديث المهمة',
  'Daily Progress': 'الإنجاز اليومي',
  'Recent daily achievements': 'أحدث الإنجازات اليومية',
  'Recorded by': 'تم التسجيل بواسطة',
  'Created by': 'أنشأها',
  'Created at': 'تاريخ الإنشاء',
  'completed': 'مكتمل',
  'Loading...': 'جارٍ التحميل...',
    'Quantity completed': 'الكمية المنجزة',
    'What did you do today?': 'ماذا أنجزت اليوم؟',
    'Work date': 'تاريخ العمل',
    'Edit': 'تعديل',
    'Delete': 'حذف',
    'Edit Task': 'تعديل المهمة',
    'Delete task': 'حذف المهمة',
    'This action cannot be undone. Are you sure you want to delete this task?': 'لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد من حذف المهمة؟',
    'Permissions': 'الصلاحيات',
    'Change password': 'تغيير كلمة المرور',
    'Change your own password': 'تغيير كلمة المرور الخاصة بك',
    'New password': 'كلمة المرور الجديدة',
    'Confirm password': 'تأكيد كلمة المرور',
    'Password must be at least 6 characters': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'Password must be at least 6 characters and both passwords must match': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل وأن تتطابق كلمتا المرور',
    'Password changed successfully': 'تم تغيير كلمة المرور بنجاح',
    'Reset password': 'إعادة تعيين كلمة المرور',
    'Temporary password': 'كلمة المرور المؤقتة',
    'Reset': 'إعادة تعيين',
    'Password reset successfully': 'تمت إعادة تعيين كلمة المرور بنجاح',
    'User': 'المستخدم',
    'Change profile photo': 'تغيير الصورة الشخصية',
    'Uploading...': 'جارٍ رفع الصورة...',
    'Profile photo updated successfully': 'تم تحديث الصورة الشخصية بنجاح',
    'Administrator permission required': 'صلاحية مدير النظام مطلوبة',
    'The General Manager has all permissions automatically.': 'المدير العام لديه جميع الصلاحيات تلقائيًا.',
    'View tasks': 'عرض المهام',
    'Create tasks': 'إنشاء المهام',
    'Edit tasks': 'تعديل المهام',
    'Delete tasks': 'حذف المهام',
    'Cancel tasks': 'إلغاء المهام',
    'Trash': 'المهملات',
    'Trash is empty': 'المهملات فارغة',
    'Deleted': 'تم الحذف',
    'Restore': 'استعادة',
    'Delete permanently': 'حذف نهائي',
    'This will permanently remove the task.': 'سيتم حذف المهمة نهائيًا ولا يمكن استعادتها.',
    'Manage task status': 'إدارة حالات المهام',
    'Evaluate tasks': 'تقييم المهام',
    'View messages': 'عرض الرسائل',
    'Send messages': 'إرسال الرسائل',
    'Manage messages': 'إدارة الرسائل',
    'View notifications': 'عرض التنبيهات',
    'View users': 'عرض المستخدمين',
    'Create users': 'إنشاء المستخدمين',
    'Edit users': 'تعديل المستخدمين',
    'Reset user passwords': 'إعادة تعيين كلمات مرور المستخدمين',
    'Manage permissions': 'إدارة الصلاحيات',
    'Edit own profile': 'تعديل الملف الشخصي',
  };

  static String tr(String key) => isArabic ? (_ar[key] ?? key) : key;
}

String tr(String key) => AppI18n.tr(key);

class T extends StatelessWidget {
  final String text;
  final TextStyle? style;
  final TextAlign? textAlign;
  const T(this.text, {super.key, this.style, this.textAlign});
  @override
  Widget build(BuildContext context) => Text(tr(text), style: style, textAlign: textAlign);
}
